### ISSUE TITLE
Solve the circular dependency issue between the SDK, compiler, and tooling

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-rs#752]
# Problem

Currently, there's a circular dependency between the SDK, compiler, and other tooling projects. This is essentially due to the SDK using `forc` in the CI builds to build Sway projects for its tests _and_ the compiler's harness tests using the SDK for testing.

# Solution

After many discussions (that happened IRL in Mexico recently, [notes here](https://www.notion.so/fuellabs/Circular-Dependencies-97494685807d49e58ad882022a41cd05)), we've settled with the following approach: 

- [x] Move the types in `packages/fuels-types/src/lib.rs` to the following repository: https://github.com/FuelLabs/fuels-types; 
  - https://github.com/FuelLabs/fuels-types/issues/1
- [x] Setup a CI environment (identical to `fuels-rs`'s CI) to publish this new package, `fuel-abi-types`, to crates.io. This new `fuel-abi-types` that contains the `ProgramABI` type will be shared between the SDK and the compiler;
  - https://github.com/FuelLabs/fuels-types/issues/2
- [x] Once `fuel-abi-types` has been published, remove the `ProgramABI`-related types from `packages/fuels-types/src/lib.rs` from `fuels-rs` and pull them from the new package, `fuel-abi-types`;
  - https://github.com/FuelLabs/fuels-rs/issues/753
- [ ] Instead of relying on `forc`, the binary, to build the Sway projects in the `fuels-rs` repo, we'll call directly `build()` from `sway`'s `forc-pkg` package. Effectively removing the dependency on `forc` itself;
  - https://github.com/FuelLabs/fuels-rs/pull/780 
- [x] Remove the dependency of `sway-core` and `forc-pkg` on `fuels-rs` and replace it with a dependency on the shared repo `fuel-abi-types`. This may _just_ work given that the dependency is already on a package named `fuel-abi-types` (the one from `fuels-rs` currently). 
  - https://github.com/FuelLabs/sway/issues/3638

Then, we'll achieve the proposed DAG (Directed Acyclic Graph):
- JSON ABI types (`fuel-abi-types`) → SDK
- JSON ABI types (`fuel-abi-types`) → `sway-core`
- `sway-core` → `forc-pkg`
- `forc-pkg` → SDK
- SDK + `sway-core` → `sdk-harness` tests

**Comment by mohammadfawaz** [comment]
I updated the description to include a compiler task that may end up being a no-op.

**Comment by digorithm** [comment]
So, upon revisiting this issue from scratch, we've decided to close it as partially resolved, given the following rationale: 

The main problem caused by the circular dependency is that, sometimes, the compiler introduces a change that requires the SDK to support this change. Because of the lack of this support, sway can’t complete a release, but the change can live on an unreleased branch.

Then, the problem has been solved without removing the circular dependency; the SDK test suite can temporarily pin an unreleased version of forc. We can release an SDK version supporting the unreleased changes in sway, meaning sway can now use this version to trigger a proper release.

So… why try and fight this circular dependency at all? This includes changing from using forc the binary to fork-pkg (which makes the code a lot messier on our side).

**Comment by mitchmindtree** [comment]
Just for some context: The reason it was originally suggested to use `forc-pkg` rather than `forc`, is that it was anticipated that `forc`'s contract unit testing support would require `fuels`, however since then we've managed to come up with an approach that doesn't require deploying contracts via `fuels`, so it's possible that it's fine to continue to use `forc` in `fuels` tests for now (now that `fuel-abi-types` is in its own repo).

---

`fuels` ideally should not be using downstream tools based on itself for its own testing - this is by definition a cycle, and was always going to cause problems. However as discussed at the retreat it's impractical for `fuels` to write all its tests in `fuel-asm` so we are attempting to be accommodating in `forc` by avoiding any dependency on `fuels` and developing workarounds where necessary.

Avoiding using `fuels` in `forc` is going to become more difficult as we begin work on the [forc package registry](https://github.com/FuelLabs/sway/issues/3752), which will involve both deploying to and reading from the fuel network within `forc-pkg`.  It would be a prime use-case for `fuels`, but as long as `fuels` uses `forc` in its tests we're unable to safely depend on `fuels` from `forc` without the potential for causing major issues in release processes.

Coming up with a workaround for the package registry and re-implementing all the logic for deploying and calling contracts may end up being a pretty major / impractically-large effort. We don't have to solve this today, but just wanted to flag this now as we'll likely need to face this cycle issue again in the coming milestone.
